# conda env create --file environment.yml
# mamba env create --file environment.yml
name: examples
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - matplotlib
  - pip
  - scikit-learn
  - seaborn
  